apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aaa 
  janus-idp.io/tekton: aaa
  backstage.io/kubernetes-id: aaa
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aaa
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  