apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: aaa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aaa 
  name: aaa
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: aaa
    weight: 100 
